name: chatify
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  kiwi: ^4.1.0
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  kiwi_generator: ^4.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: RedHatText
      fonts:
        - asset: assets/font/RedHatText-Bold.ttf
          weight: 700
        - asset: assets/font/RedHatText-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/font/RedHatText-SemiBold.ttf
          weight: 600
        - asset: assets/font/RedHatText-Medium.ttf
          weight: 500
        - asset: assets/font/RedHatText-Regular.ttf
          weight: 400
        - asset: assets/font/RedHatText-Light.ttf
          weight: 300

    - family: BarlowCondensed
      fonts:
        - asset: assets/font/BarlowCondensed-Bold.ttf
          weight: 700
        - asset: assets/font/BarlowCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/font/BarlowCondensed-Medium.ttf
          weight: 500
        - asset: assets/font/BarlowCondensed-Regular.ttf
          weight: 400
        - asset: assets/font/BarlowCondensed-Light.ttf
          weight: 300
